// Generated by gencpp from file learning/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARNING_MESSAGE_ADDTWOINTS_H
#define LEARNING_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learning/AddTwoIntsRequest.h>
#include <learning/AddTwoIntsResponse.h>


namespace learning
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learning::AddTwoInts > {
  static const char* value()
  {
    return "learning/AddTwoInts";
  }

  static const char* value(const ::learning::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learning::AddTwoInts > 
template<>
struct MD5Sum< ::learning::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning::AddTwoInts >::value();
  }
  static const char* value(const ::learning::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learning::AddTwoInts > 
template<>
struct DataType< ::learning::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning::AddTwoInts >::value();
  }
  static const char* value(const ::learning::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learning::AddTwoInts > 
template<>
struct MD5Sum< ::learning::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning::AddTwoInts >::value();
  }
  static const char* value(const ::learning::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learning::AddTwoInts > 
template<>
struct DataType< ::learning::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning::AddTwoInts >::value();
  }
  static const char* value(const ::learning::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_MESSAGE_ADDTWOINTS_H
